INSERT INTO CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME) VALUES (1,'Avishka');
INSERT INTO CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME) VALUES (2,'Ayantha');
INSERT INTO CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME) VALUES (3,'Anushka');

INSERT INTO ORDERS (ORDER_ID,PRICE,QUANTITY,CUSTOMER_ID) VALUES (1,1000,10,1);
INSERT INTO ORDERS (ORDER_ID,PRICE,QUANTITY,CUSTOMER_ID) VALUES (2,1000,50,1);
INSERT INTO ORDERS (ORDER_ID,PRICE,QUANTITY,CUSTOMER_ID) VALUES (3,1500,90,2);
INSERT INTO ORDERS (ORDER_ID,PRICE,QUANTITY,CUSTOMER_ID) VALUES (4,1000,10,3);
INSERT INTO ORDERS (ORDER_ID,PRICE,QUANTITY,CUSTOMER_ID) VALUES (5,150,10,3);
INSERT INTO ORDERS (ORDER_ID,PRICE,QUANTITY,CUSTOMER_ID) VALUES (6,10400,540,3);